image: docker:latest
services:
  - docker:dind

stages:
  - test
  - deploy

unit_test:
  stage: test
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
  when: manual
  script:
    - sudo apt-get install -y docker-compose
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build
    - sudo docker-compose -f docker-compose.yml run --rm node npm test
    - sudo docker-compose -f docker-compose.yml down
e2e_test:
  stage: test
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
  when: manual
  script:
    - sudo apt-get install -y docker-compose
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build
    - sudo docker-compose -f docker-compose.yml run --rm node npm run test:e2e
    - sudo docker-compose -f docker-compose.yml down
deployment:
  stage: deploy
  only:
    - master
  script:
    - sudo apt-get install -y docker-compose
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build
    - sudo docker-compose -f docker-compose.yml up -d
  when: manual