version: '3'
services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    command: "npm start"
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - mongo
    environment: 
      - MONGO_URI=mongodb://mongo:27017/base-store
      - MONGO_URI_TEST=mongodb://mongo:27017/test-base-store
      - JWT_SECRET=VERYSECRET
      - JWT_EXPIRES=3600
      - SWAGGER_PASS=9hX_G3z!UHPMV@3
    volumes: 
    - ./:/home/dev/store-back
  mongo:
    image: "mongo:4.2.11-bionic"
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /home/data:/data/db