export default {
  // User
  READ_USER: 'read_user',
  CREATE_USER: 'create_user',
  UPDATE_USER: 'update_user',
  DELETE_USER: 'delete_user',
  // Role
  READ_ROLE: 'read_role',
  CREATE_ROLE: 'create_role',
  UPDATE_ROLE: 'update_role',
  DELETE_ROLE: 'delete_role',
  // Category
  READ_CATEGORY: 'read_category',
  CREATE_CATEGORY: 'create_category',
  UPDATE_CATEGORY: 'update_category',
  DELETE_CATEGORY: 'delete_category',
  // Product
  READ_PRODUCT: 'read_product',
  CREATE_PRODUCT: 'create_product',
  UPDATE_PRODUCT: 'update_product',
  DELETE_PRODUCT: 'delete_product',
  // Brand
  READ_BRAND: 'read_brand',
  CREATE_BRAND: 'create_brand',
  UPDATE_BRAND: 'update_brand',
  DELETE_BRAND: 'delete_brand',
  // Banner
  READ_BANNER: 'read_banner',
  CREATE_BANNER: 'create_banner',
  UPDATE_BANNER: 'update_banner',
  DELETE_BANNER: 'delete_banner',
  // Comment
  READ_COMMENT: 'read_comment',
  UPDATE_COMMENT: 'update_comment',
  DELETE_COMMENT: 'delete_comment',
  // Article
  READ_ARTICLE: 'read_article',
  CREATE_ARTICLE: 'create_article',
  UPDATE_ARTICLE: 'update_article',
  DELETE_ARTICLE: 'delete_article',
  // Coupon
  READ_COUPON: 'read_coupon',
  CREATE_COUPON: 'create_coupon',
  UPDATE_COUPON: 'update_coupon',
  DELETE_COUPON: 'delete_coupon',
  // Basket
  READ_BASKET: 'read_basket',
  CREATE_BASKET: 'create_basket',
  UPDATE_BASKET: 'update_basket',
  DELETE_BASKET: 'delete_basket',
  // Payment
  READ_PAYMENT: 'read_payment',
  CREATE_PAYMENT: 'create_payment',
  UPDATE_PAYMENT: 'update_payment',
  DELETE_PAYMENT: 'delete_payment',
};
